config/routes.rb
Tracker::Application.routes.draw do
  root to: 'dashboard#index'

  resources :dashboard
  resources :courses
  resources :groups
  resources :clients
  resources :users
  resources :status_report
  resources :records
  resources :search

  get 'search/:q', to: 'search#index'

  

end

app/models/group.rb
class Group < ActiveRecord::Base
	include PgSearch
	multisearchable :against => [:name]

	belongs_to :client
	has_many :users

	scope :by_client, ->(id) { where(:client_id => id)}
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.page(params[:page]).per_page(10)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/views/groups/_form.html.erb
<div class="widget wgreen widget-width">
  <div class="widget-head">
    <div class="pull-left"><%= yield(:title) %></div>
    <div class="clearfix"></div>
  </div>
  <div class="widget-content padd">
<!-- ################### -->

<%= form_for(@group, :html => { :class => "form-horizontal" }) do |f| %>
  
  <% if @group.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@group.errors.count, "error") %> prohibited this client from being saved:</h4>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :client_id, "Company", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.collection_select :client_id, Client.all, :id, :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.submit :class => "btn btn-primary btn-lg" %>
    </div>
  </div>
  
<% end %>


 <!-- ################### -->
  </div>
</div>

app/views/groups/edit.html.erb
<% provide(:title, 'Edit Group') %>
<%= render 'form' %>

app/views/groups/index.html.erb
<% provide(:title, 'Group List') %>

<div class="table-responsive widget-width ">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
          <th>Name</th>
          <th>Company</th>
          <th>Show</th>
          <th>Edit</th>
          <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @groups) do |group| %>
            <td><%= group.name %></td>
            <td><%= group.client.name %></td>
            <td><%= link_to 'Show', group, :class => "btn btn-default btn-primary" %></td>
            <td><%= link_to 'Edit', edit_group_path(group), :class => "btn btn-default " %></td>
            <td><%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default " %></td>
      <% end %>
    </tbody>
  </table>
    <div class="widget-foot">
    <ul class="pagination pull-right">
      <%= will_paginate @groups, renderer: BootstrapPagination::Rails, bootstrap: 3 %>
    </ul>
    <div class="clearfix"></div>
  </div>
</div>

app/views/groups/new.html.erb
<% provide(:title, 'New Group') %>

<div class="widget wgreen widget-width">
  <div class="widget-head">
    <div class="pull-left"><%= yield(:title) %></div>
    <div class="clearfix"></div>
  </div>
  <div class="widget-content padd">

<%= render 'form' %>

  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title, 'Group Profile') %>
<div class="widget wgreen widget-width">
  <div class="widget-head">
    <div class="pull-left"><%= yield(:title) %></div>
    <div class="clearfix"></div>
  </div>
  <div class="widget-content padd">
<!-- ################### -->
    <div class="table-responsive widget-width ">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Group Name</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
            <tr>
            <td><%= @group.name %></td>
            <td><%= link_to "Edit", edit_group_path(@group), :class => 'btn btn-primary' %></td>
            <td><%= link_to "Back", groups_path, :class => 'btn btn-default' %></td>
            </tr>
        </tbody>
      </table>
    </div>
 <!-- ################### -->
  </div>
</div>