config/routes.rb
Tracker::Application.routes.draw do
  root to: 'dashboard#index'

  resources :dashboard
  resources :courses
  resources :groups
  resources :clients
  resources :users
  resources :status_report
  resources :records
  resources :search

  get 'search/:q', to: 'search#index'

  

end

app/models/client.rb
class Client < ActiveRecord::Base
	include PgSearch
	multisearchable :against => [:name]

	has_many :groups
	has_many :users
	has_many :records, through: :users
end

app/models/course.rb
class Course < ActiveRecord::Base
	include PgSearch
	multisearchable :against => [:name]

end

app/models/group.rb
class Group < ActiveRecord::Base
	include PgSearch
	multisearchable :against => [:name]

	belongs_to :client
	has_many :users

	scope :by_client, ->(id) { where(:client_id => id)}
end

app/models/record.rb
class Record < ActiveRecord::Base
	
	belongs_to :user
	has_one :course
	has_one :client, through: :user
	has_one :group, through: :user
end

app/models/status_report.rb
class StatusReport < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	include PgSearch
	multisearchable :against => [:first_name, :last_name, :full_name]

	belongs_to :client
	has_many :records
	belongs_to :group

	default_scope :order => 'users.first_name ASC, users.last_name ASC'
	scope :by_client, ->(id) { where(:client_id => id)}

	def full_name
	@full_name = "#{first_name} #{last_name}"
	end
  
	def self.text_search(query)
	  if query.present?
	    rank = <<-RANK
	      ts_rank(to_tsvector(name), plainto_tsquery(#{sanitize(query)})) +
	      ts_rank(to_tsvector(content), plainto_tsquery(#{sanitize(query)}))
	    RANK
	    where("to_tsvector('english', name) @@ :q or to_tsvector('english', content) @@ :q", q: query).order("#{rank} desc")
	  else
	    scoped
	  end
	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.page(params[:page]).per_page(10)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
	helper_method :find_course

  def activity
  	@activity = ActivityReport.new
  	record = Record.find(params[:id]) 
  	@activity.user_name = User.find(record.user_id)
  	course = Course.find(record.course_id)
  	@activity.course_name = course.name
  	@activity.score = record.score
  	@activity.pass_fail = record.pass
  	@activity.date_taken = record.completed_date
  	@activity.requal_date = record.completed_date + course.requal_interval.months
  end


  def course_name(course_id)
  	@course_name = Course.find(course_id)
  	@course_name = @course_name.name
  end

  def status
  end
  def report_params
    params.require(:record).permit(:course_id, :score, :pass, :completed_date, :user_id, :requal_date)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index
		if params.include?(:q)
			@results = User.multisearch(params[:q])
			raise @results.inspect
		else
			@results = []
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @users = User.order("last_name, first_name").page(params[:page]).per_page(10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    # raise  params.inspect

    @user = User.new(user_params)
    @user.client_id = params[:client][:client_id]

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      @user.client_id = params[:client][:client_id]
      @user.group_id = params[:group_id] ||= nil
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, {client: :client_id}, :group_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = 'Records Tracker'
		if page_title.empty?
		  base_title
		else
		  "#{base_title} | #{page_title}"
		end
	end

	def badge_expired
		rec = Record.where("pass = ? AND requal_date < ?", true, Date.today)
		@badge_expired = rec.length
	end

	def badge_soon
		rec = Record.where("pass = ? AND requal_date < ? AND requal_date > ?", true, Date.today + 3.months, Date.today)
		@badge_soon = rec.length
	end

	def badge_good
		rec = Record.where("pass = ? AND requal_date > ?", true, Date.today + 3.months)
		@badge_good = rec.length
	end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/records_helper.rb
module RecordsHelper

end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/status_report_helper.rb
module StatusReportHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'shared/meta' %>
  <%= render 'shared/stylesheets' %>
  <%= render 'shared/shiv' %>
</head>

<body>
		<%= render 'shared/nav' %>
		<%= render 'shared/brand' %>
		<div class="content">
		<%= render 'shared/sidebar' %>
		  	<!-- Main bar -->
		  	<div class="mainbar">
		      <!-- Page heading -->
		      <div class="page-head">
		        <h2 class="pull-left"><%= yield(:title) %></h2>
		        <div class="clearfix"></div>
		      </div>
		      <!-- Page heading ends -->
			    <!-- Matter -->
			    <div class="matter">
		          <div class="container-fluid">
					  <%= render 'shared/alerts' %>
					  <%= yield %>
				  </div>
			    </div>
				<!-- Matter ends -->
		    </div>
		   <!-- Mainbar ends -->	    	
		   <div class="clearfix"></div>
		</div>
  	<%= debug(params) if Rails.env.development? %>
	<%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_alerts.html.erb
<div class="container">

	<% flash.each do |name, msg| %>
		<%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
		  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		  <%= msg %>
		<% end %>
	<% end %>

</div>

app/views/shared/_brand.html.erb
<header>
  <div class="container">
    <div class="row brand-row">

      <!-- Logo section -->
      <div class="col-md-4">
        <!-- Logo. -->
        <div class="logo">
          <a href="/"><%= image_tag "oasis_logo.png", :class => "media-object pull-left", :size => '200x60' %></a>
        </div>
        <!-- Logo ends -->
      </div>

      <div class="table-responsive center">
        <!-- Buttons -->
        <ul class="nav nav-pills pull-left">
        <li>
          <a>
            <i class="icon-remove-sign"></i> Expired <span class="label label-danger"><%= @expired = badge_expired %></span> 
          </a>
        </li>
        <li>
          <a>
            <i class="icon-minus-sign"></i> Soon <span class="label label-warning"><%= @soon = badge_soon %></span> 
          </a>
        </li>
        <li>
          <a>
            <i class="icon-thumbs-up"></i> Good <span class="label label-success"><%= @good = badge_good %></span> 
          </a>
        </li>           
        </ul>

        <ul class="nav nav-pills pull-right">
        <li>
          <a href="/records/new">
            <i class="icon-plus"></i> Add Record
          </a>
        </li>           
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_footer.html.erb
<footer class="footer-border">
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
            <!-- Copyright info -->
            <p class="copy">Copyright © <%= Date.today.year %> | <%= link_to "The Oasis Initiative", 'http://www.oasisinitiative.net' %> </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_meta.html.erb
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="Records Tracker from The Oasis Initiative">
  <meta name="author" content="Travis Payne">

app/views/shared/_nav.html.erb
<div class="navbar navbar-fixed-top bs-docs-nav" role="banner">
  <div class="conjtainer">
    <!-- Menu button for smallar screens -->
    <div class="navbar-header">
    <button class="navbar-toggle btn-navbar" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
    <span>Menu</span>
    </button>
    <!-- Site name for smallar screens -->
    <%= link_to "Records Tracker", dashboard_index_path, :class => "navbar-brand hidden-lg" %>
  </div>
    <!-- Navigation starts -->
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation"> 
      <!-- Search form -->
      <form class="navbar-form navbar-left" role="search" accept-charset="UTF-8" action="/search" method="get">
        <div class="form-group">
          <input name="q" type="text" class="form-control" placeholder="Search">
        </div>
        <button method="get" class="btn btn-default"><i class="icon-search"></i></button>
      </form>
      <!-- Add Links -->
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown pull-right">            
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-circle"></i> Add Items <b class="caret"></b>              
          </a>
          
          <!-- Dropdown menu -->
          <ul class="dropdown-menu">
            <li><%= link_to "New Record", new_record_path %></li>
            <li><%= link_to "New Company", new_client_path %></li>
            <li><%= link_to "New User", new_user_path %></li>
            <li><%= link_to "New Group", new_group_path %></li>
            <li><%= link_to "New Course", new_course_path %></li>
          </ul>
        </li>
      </ul>
      <!-- View Links -->
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown pull-right">            
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-circle-blank"></i> View Items <b class="caret"></b>              
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu">
            <li><%= link_to "Activity Report", records_path %></li>
            <li><%= link_to "Status Report", status_report_index_path %></li>
            <li><%= link_to "Company List", clients_path %></li>
            <li><%= link_to "Groups List", groups_path %></li>
            <li><%= link_to "Users List", users_path %></li>
            <li><%= link_to "Course List", courses_path %></li>
          </ul>
        </li>
      </ul>
      <!-- Admin Links -->
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown pull-right">            
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-user"></i> Admin <b class="caret"></b>              
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu">
            <li><a href="#"><i class="icon-user"></i> Profile</a></li>
            <li><a href="#"><i class="icon-cogs"></i> Settings</a></li>
            <li><a href="login.html"><i class="icon-off"></i> Logout</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/shared/_shiv.html.erb
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "bootstrap-ie" %>
  <![endif]-->

app/views/shared/_sidebar.html.erb
<!-- Sidebar -->
<div class="sidebar">
    <div class="sidebar-dropdown"><a>Navigation</a></div>

    <!--- Sidebar navigation -->
    <!-- If the main navigation has sub navigation, then add the class "has_sub" to "li" of main navigation. -->
    <ul id="nav">
      <!-- Main menu with font awesome icon -->
      <li><a href="/"><i class="icon-dashboard"></i> Dashboard </a>
        <!-- Sub menu markup 
        <ul>
          <li><a href="#">Submenu #1</a></li>
          <li><a href="#">Submenu #2</a></li>
          <li><a href="#">Submenu #3</a></li>
        </ul>-->
      </li>
      
      <li class="has_sub"><a><i class="icon-bar-chart"></i> Reports  <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
        <ul>
          <li><%= link_to "Activity Report", records_path %></li>
          <li><%= link_to "Status Report", status_report_index_path %></li>
        </ul>
      </li>  
      
      <li class="has_sub"><a><i class="icon-suitcase"></i> Companies <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
        <ul>
          <li><%= link_to "New Company", new_client_path %></li>
          <li><%= link_to "Companies List", clients_path %></li>
        </ul>
      </li> 

      <li class="has_sub"><a><i class="icon-group"></i> Groups <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
        <ul>
          <li><%= link_to "New Group", new_group_path %></li>
          <li><%= link_to "Groups List", groups_path %></li>
        </ul>
      </li> 
      
      <li class="has_sub"><a><i class="icon-user"></i> Users <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
        <ul>
          <li><%= link_to "New User", new_user_path %></li>
          <li><%= link_to "User List", users_path %></li>
        </ul>
      </li> 
    
      <li class="has_sub"><a><i class="icon-book"></i> Courses <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
        <ul>
          <li><%= link_to "New Course", new_course_path %></li>
          <li><%= link_to "Courses List", courses_path %></li>
        </ul>
      </li> 

    </ul>
</div>
<!-- Sidebar ends -->

app/views/shared/_stylesheets.html.erb
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>