config/routes.rb
Tracker::Application.routes.draw do
  root to: 'dashboard#index'

  resources :dashboard
  resources :courses
  resources :groups
  resources :clients
  resources :users
  resources :status_report
  resources :records
  resources :search

  get 'search/:q', to: 'search#index'

  

end

app/models/record.rb
class Record < ActiveRecord::Base
	
	belongs_to :user
	has_one :course
	has_one :client, through: :user
	has_one :group, through: :user
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    #raise  params.inspect
      if params.include?(:client)
        @records = User.find_by_id(params[:client][:user_id])
        if @records.nil?
          flash[:error] = "Please select a Company and User"
        elsif
          @records = @records.records.page(params[:page]).per_page(10)
        end
      else
        @records = Record.page(params[:page]).per_page(10)
      end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @course = Course.find(@record.course_id)
  end

  # GET /records/new
  def new
    @record = Record.new
    @clients = Client.all
    @groups = Group.all
    @users = User.all
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    interval = set_requal(@record)
    @record.requal_date = @record.completed_date + interval.months
    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @record }
      else
        format.html { render action: 'new' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:course_id, :score, :pass, :completed_date, :user_id, :requal_date)
    end

    def set_requal(record)
      course = Course.find(record.course_id)
      interval = course.requal_interval
    end

end

app/helpers/records_helper.rb
module RecordsHelper

end

app/views/records/_form.html.erb
<div class="widget wgreen widget-width">
  <div class="widget-head">
    <div class="pull-left"><%= yield(:title) %></div>
    <div class="clearfix"></div>
  </div>
  <div class="widget-content padd">
<!-- ################### -->

    <%= form_for(@record, :html => { :class => "form-horizontal" }) do |f| %>
      <% if @record.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h4>

          <ul>
          <% @record.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
        

      <div class="form-group">
        <%= label :client, :client_id, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= collection_select(:client, :client_id, Client.find(:all, :order => "name"), :id, :name, {:prompt => true}, {:class=>'form-control'}) %>
        </div>
      </div>

      <div class="form-group">
        <%= label :user, :user_id, :class => "col-lg-2 control-label", :id => "user-header" %>
        <div class="col-lg-10">
          <%= f.grouped_collection_select( :user_id, Client.order(:name), :users, :name, :id, :full_name, {:prompt => true}, {:class=>'form-control'}) %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :course_id, :class => "col-lg-4 control-label" %>
        <div class="col-lg-10">
          <%= f.collection_select(:course_id,  Course.find(:all, :order => "name"), :id, :name, {:prompt => true}, {:class=>"form-control"}) %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :completed_date, :class => "col-lg-4 control-label control-label" %>
        <div class="col-lg-10">
          <%= f.date_select :completed_date, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :score, :class => "col-lg-4 control-label" %>
        <div class="col-lg-2">
          <%= f.text_field :score, :class => "form-control" %>
        </div>
      </div>
          <div class="form-group">
        <%= f.label :pass, :class => "col-lg-4 control-label" %>
        <div class="col-lg-10">
          <%= f.check_box :pass %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10">
          <%= f.submit :class => "btn btn-primary btn-lg push-right" %>
        </div>
      </div>
    <% end %>

 <!-- ################### -->
  </div>
</div>

app/views/records/_index_filter.html.erb
<div class="widget wgreen widget-width center">
  <div class="widget-head">
    <div class="pull-left">Filtering Options</div>
    <div class="pull-right">
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="widget-content ">
<!-- ################### -->

  <div class="table-responsive">
    <form method="get" action="/records">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Company</th>
            <th id="user-header">User</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
        <!-- collection_select(object, method, collection, value_method, text_method, options = {}, html_options = {}) -->
        <td><%= collection_select(:client, :client_id, Client.find(:all, :order => "name"), :id, :name, {:prompt => true}, {:class=>'form-control'}) %></td>
        <td><%= grouped_collection_select(:client, :user_id, Client.order(:name), :users, :name, :id, :full_name, {:prompt => true}, {:class=>'form-control'}) %></td>
        <td><%= submit_tag 'Filter', :class => "btn btn-primary form-control" %></td>
        </tbody>
      </table>
    </form>
  </div>

 <!-- ################### -->
  </div>
</div>

app/views/records/edit.html.erb
<% provide(:title, 'Edit Record') %>

<%= render 'form' %>

app/views/records/index.html.erb
<% provide(:title, 'Activity Report') %>

<%= render 'index_filter' %>

<div class="table-responsive widget-width  widget-width">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>

        <th>User</th>
        <th>Company</th>
        <th>Group</th>
        <th>Course</th>
        <th>Score</th>
        <th>Pass / Fail</th>
        <th>Completed Date</th>
        <th>Requal Date</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @records) do |record| %>
            <td><%= record.user.full_name %></td>
            <td><%= record.user.client.name %></td>
            <td><%= record.user.group.name %></td>
            <td><%= get_course_name(record.course_id) %></td>
            <td><%= record.score %></td>
            <% if record.pass == true %>
            <td style="color:green;">Passed</td>
            <% else %>
            <td style="color:red;">Failed</td>
            <% end %>
            <td><%= record.completed_date %></td>
            <td><%= record.requal_date %></td>

            <td><%= link_to 'Show', record, :class => "btn btn-default btn-primary" %></td>
            <td><%= link_to 'Edit', edit_record_path(record), :class => "btn btn-default " %></td>
            <td><%= link_to 'Delete', record, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default " %></td>
      <% end %>
    </tbody>
  </table>
  <div class="widget-foot">
    <ul class="pagination pull-right">
      <%= will_paginate @records, renderer: BootstrapPagination::Rails, bootstrap: 3 %>
    </ul>
    <div class="clearfix"></div>
  </div>
</div>

app/views/records/new.html.erb
<% provide(:title, 'New Record') %>
<%= render 'form' %>

app/views/records/show.html.erb
<% provide(:title, 'Record Details') %>
<div class="widget wgreen widget-width">
  <div class="widget-head">
    <div class="pull-left"><%= yield(:title) %></div>
    <div class="clearfix"></div>
  </div>
   <div class="widget-content patd">
<!-- ################### -->
    <div class="table-responsive widget-width ">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Company</th>
            <th>User</th>
            <th>Group</th>
            <th>Course</th>
            <th>Completed Date</th>
            <th>Requal Date</th>
            <th>Score</th>
            <th>Pass / Fail</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td><%= @record.user.client.name %></td>
              <td><%= @record.user.full_name %></td>
              <td><%= @record.user.group.name %></td>
              <td><%= @course.name %></td>
              <td><%= @record.completed_date %></td>
              <td><%= @record.requal_date %></td>
              <td><%= @record.score %></td>
              <% if @record.pass == true %>
               <td style="color:green;">Passed</td>
              <% else %>
                <td style="color:red;">Failed</td>
              <% end %>
              <td><%= link_to "Edit", edit_record_path(@record), :class => 'btn btn-primary' %></td>
              <td><%= link_to "Back", records_path, :class => 'btn btn-default' %></td>
            </tr>
        </tbody>
      </table>
    </div>
 <!-- ################### -->
  </div>
</div>